[package]
name = "compressed_map"
version = "0.1.0"
edition = "2021"

[features]
threading = []

[dependencies]
# TODO: pin hashes
serde = { version = "1.0", features = ["derive"] }
siphasher = "0.3"
rand = "0.8.5"

[dev-dependencies]
serde_json = "1.0"

[target.'cfg(bench)'.dev-dependencies]
criterion = "0.3"

[[bench]]
name = "matrix_ops"
harness = false

[[bench]]
name = "uniform"
harness = false

[[bench]]
name = "nonuniform"
harness = false

[profile.release]
lto = true
#panic = "abort"
