[package]
name = "compressed_map"
version = "0.1.0"
edition = "2021"

# TODO: pin hashes

[dependencies]
# serde = { version = "1.0", features = ["derive"] }
siphasher = "0.3"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "matrix_ops"
harness = false

[[bench]]
name = "uniform"
harness = false

[[bench]]
name = "nonuniform"
harness = false

[profile.release]
lto = true
#panic = "abort"
